#run in terminal: conda env create -f environment.yml
name: SpatialInferCNV
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-essentials
  - r-base
  - bioconductor-infercnv
  - r-seurat
  - r-phylogram
  - r-hdf5r
  - r-devtools
